// Mocks generated by Mockito 5.4.6 from annotations
// in app_sanitaria/test/domain/usecases/reviews/get_average_rating_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app_sanitaria/core/error/failures.dart' as _i5;
import 'package:app_sanitaria/domain/entities/review_entity.dart' as _i6;
import 'package:app_sanitaria/domain/repositories/reviews_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReviewsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewsRepository extends _i1.Mock implements _i3.ReviewsRepository {
  MockReviewsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ReviewEntity>>>
      getReviewsByProfessional(String? professionalId) => (super.noSuchMethod(
            Invocation.method(
              #getReviewsByProfessional,
              [professionalId],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.ReviewEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ReviewEntity>>(
              this,
              Invocation.method(
                #getReviewsByProfessional,
                [professionalId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ReviewEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ReviewEntity>> addReview(
          _i6.ReviewEntity? review) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReview,
          [review],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ReviewEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.ReviewEntity>(
          this,
          Invocation.method(
            #addReview,
            [review],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ReviewEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> deleteReview(
          String? reviewId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReview,
          [reviewId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteReview,
            [reviewId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getAverageRating(
          String? professionalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAverageRating,
          [professionalId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #getAverageRating,
            [professionalId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getReviewsCount(
          String? professionalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviewsCount,
          [professionalId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getReviewsCount,
            [professionalId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);
}
